[package]
name = "scraper"
version = "0.7.0"

description = "HTML parsing and querying with CSS selectors"
keywords = ["html", "css", "selector", "scraping"]

authors = [
    "Curtis McEnroe <june@causal.agency>",
    "Vivek Kushwaha <yoursvivek@gmail.com>",
]
license = "ISC"

repository = "https://github.com/programble/scraper"
readme = "README.md"

[dependencies]
cssparser = "0.24.1"
ego-tree = "0.5.0"
html5ever = "0.22.0"
matches = "0.1.6"
selectors = "0.20.0"
tendril = "0.4.0"
smallvec = "0.6.0"
